name: Heroku push for staging
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
    environment:
      name: test
    steps:
      - uses: actions/checkout@v2
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      RAILS_ENV: staging
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GITHUB_CLIENT_ID: GITHUB_CLIENT_ID # dummy
      GITHUB_CLIENT_SECRET: GITHUB_CLIENT_SECRET # dummy
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Setup yarn and node
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update -qq
          sudo apt-get install -y nodejs yarn
          yarn install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Install dependencies
        run: bundle install
      - name: Setup Database
        run: |
          bin/rails db:migrate
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # https://dashboard.heroku.com/account
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
  e2e-test:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    environment:
      name: staging
    steps:
      - name: Run Autify TestPlan
        uses: a-know/actions-autify-light@main
        with:
          project_id: ${{ secrets.AUTIFY_PROJECT_ID }}
          testplan_id: ${{ secrets.AUTIFY_TESTPLAN_ID }}
        env:
          AUTIFY_PERSONAL_TOKEN: ${{ secrets.AUTIFY_PERSONAL_TOKEN }}
